### ISSUE TITLE
Doesn't seem to work with angular-cli

### ISSUE THREAD

**Issue by ericel** [Shailu4u/ng-masonry-grid#1]
No errors with log, the behavior wasn't there. Does cli needs additional setup?

**Comment by pette9** [comment]
I have the same behaviour but the problem seems to be imagesloaded firing early when in production. The layouts without images work fine with the latest angular-cli

**Comment by ericel** [comment]
It adds this extra scrollbar in the page! I guess it's because of the css. Haven't had time to really check things out.  It will be an awesome module with a few tweaks.

**Comment by Shailu4u** [comment]
@pette9 Can you please elaborate if there are any errors.

**Comment by pette9** [comment]
@Shailu4u There are no errors when I build for production with angular-cli "1.6.5" but when in production, The `ImagesLoaded` console log appears way before the images are loaded and the behaviour that follows is similar to what I get when I remove `[useImagesLoaded]="true"` or set `[useImagesLoaded]="false"` in development. For a masonry grid with no images, or few thumb sized images, it works fine for both development and production modes.

**Comment by ericel** [comment]
@Shailu4u  is there a way to call the reloadItems from the service. I checked the service I  didn't see any such method. It would be nice especially as when I delete an item as for now , the layout breaks. So It would be nice to call reload layout on item delete complete.

**Comment by Shailu4u** [comment]
@ericel

**Comment by Shailu4u** [comment]
@ericel @pette9 Updated the library with new version @1.2.0. 
New features implemented such Add, Append, Prepend, RemoveItem, RemoveFirstItem and RemoveAllItems, onNgMasonryInit event.

**Comment by Shailu4u** [comment]
@pette9 Fixed all bugs related to imagesLoaded etc.

**Comment by Shailu4u** [comment]
@ericel Now we can get Masonry instance using onNgMasonryInit event. We can use all available Masonry methods with that instance such as reloadItems(), layout() etc

**Comment by Shailu4u** [comment]
Updated the package with all fixes. Hence closing the issue.
