### ISSUE TITLE
Support for Angular 6

### ISSUE THREAD

**Issue by eagerowl** [Shailu4u/ng-masonry-grid#12]
Hi, has anyone had any luck getting this to run in Angular 6?

**Comment by trietsch** [comment]
@eagerowl what issue are you running into?

**Comment by JoaoPortella** [comment]
Hi @trietsch 

**I have this error when install...**
npm WARN ng-masonry-grid@1.2.5 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-masonry-grid@1.2.5 requires a peer of @angular/common@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ng-masonry-grid@1.2.5 requires a peer of rxjs@^5.1.0 but none is installed. You must install peer dependencies yourself.

**and this when try to compile...**
ERROR in node_modules/ng-masonry-grid/ng-masonry-grid.interface.d.ts(1,10): error TS2305: Module '"C:/Desenv/RiskOne/v3/sistema/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng-masonry-grid/ng-masonry-grid.service.d.ts(2,10): error TS2305: Module '"C:/Desenv/RiskOne/v3/sistema/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.

**My angular version is 6.1.0**

**Thanks!**

**Comment by Shailu4u** [comment]
Updated the ng-masonry-grid module to new angular version 6+. 
Use latest npm pacakage: npm i --save ng-masonry-grid@1.3.0
