### ISSUE TITLE
Items below each other instead of being in a grid

### ISSUE THREAD

**Issue by mruknowme** [Shailu4u/ng-masonry-grid#13]
I am using items as `@Input()` and when items change, grid changes but all items are just displayed below each other, although I checked in inspector the container width allows to fit in more.

Any ideas why this might be happening?

**Comment by Shailu4u** [comment]
Can you please elaborate the issue if any errors.
when the grid items changes, try to use setTimeout and initialize the grid.

**Comment by kaiwalyapowle** [comment]
How to initialize the grid ?

**Comment by Shailu4u** [comment]
@kaiwalyapowle , please find documentation for initializing the grid in README.md.
@mruknowme , please feel free to reopen the issue in case you find any more.
