### ISSUE TITLE
Images reordered on page refresh

### ISSUE THREAD

**Issue by jigneshInd** [Shailu4u/ng-masonry-grid#17]
In Grid layout when we refresh page it reorder the images, but i want to show ordered images like first images should always come first.

**Comment by Shailu4u** [comment]
@jigneshInd , the images will load dynamically and upon page refresh, the order of images will be different each time. If you want ordered items always, use this._masonry.reOrderItems() method in masonry initialization callback (onNgMasonryInit); 

Checkout https://github.com/Shailu4u/ng-masonry-grid/issues/2#issuecomment-434256053 might be helpful.
