### ISSUE TITLE
Animations doesn't work in production.

### ISSUE THREAD

**Issue by JNodbrant** [Shailu4u/ng-masonry-grid#3]
The animations are working fine in production but as soon as you build the app for production they stop working without errros.

**Comment by Shailu4u** [comment]
Its working in prod, try running the below demo version as below.
npm install
npm run start
Then go to localhost:8080
Demo version: https://github.com/Shailu4u/ng-masonry-grid-demo

**Comment by Shailu4u** [comment]
Animation effects will be applied only to the grid items which are newly added in viewport. Apart from our custom animations on scroll, by default Masonry has its own transition on grid items when we use "transitionDuration: '0.4s'," property.
I tried using **ng build --prod** and running the demo project. All animation effects on scroll and default Masonry's transitions are working fine.
[Preview](http://ng-masonry-grid-demo.herokuapp.com/)

**Comment by Shailu4u** [comment]
Closing the issue, 
@JNodbrant feel free to reopen the issue, still if there are any animation issues.
