### ISSUE TITLE
Error when not using images as grid item

### ISSUE THREAD

**Issue by iplaksiy** [Shailu4u/ng-masonry-grid#6]
Getting the following errors in the console when trying to init a collection of items _**without**_ an image:

`Cannot read property 'slice' of undefined`
`at SubClass.proto._getColGroupY (masonry.js:160)`
`at SubClass.proto._getHorizontalColPosition (masonry.js:177)`
`at SubClass.proto._getItemLayoutPosition (masonry.js:108)`
`at SubClass.eval (outlayer.js:322)`
`at Array.forEach (<anonymous>)`
`at SubClass.proto._layoutItems (outlayer.js:320)`
`at SubClass.proto.layoutItems (outlayer.js:288)`
`at SubClass.proto.appended (outlayer.js:689)`
`at NgMasonryGridService.add (ng-masonry-grid.umd.js:405)`
`at NgMasonryGridComponent.add (ng-masonry-grid.umd.js:736)`

**Template:**
```
:host >>> .item {
   width: 200px;
   height: 200px;
}

```
```
<ng-masonry-grid 
[useAnimation]="true">
  <ng-masonry-grid-item 
    *ngFor="let item of items;">
    <div class="item">{{item.name}}</div>
  </ng-masonry-grid-item>
</ng-masonry-grid>
```

The items show up in view and render, however, the error still fires. 

Any ideas?

**Comment by Shailu4u** [comment]
Fixed and updated code in version 1.2.5

**Comment by nithindan** [comment]
Getting this issue again .
Im working on Angular 6 .
Your demo link also have same issue while clicking on effect

**Comment by howHighUR** [comment]
Same issue

**Comment by veksen** [comment]
Well, if you look at the "fix", it's no wonder that it is still happening. The fix includes a bunch of nested setTimeout. This isn't how you deal with async code :( https://github.com/Shailu4u/ng-masonry-grid/commit/61df5505855259a02a0da8fd025d286923ae7617
