### ISSUE TITLE
Define 3 columns instead of 5

### ISSUE THREAD

**Issue by gbesset** [Shailu4u/ng-masonry-grid#8]
Hello

I spend some hours trying to define 3 columns but i still have 5

As explained in the documentation, and on https://masonry.desandro.com/options.html I define in masonryOptions
* . itemSelector: '.grid-item'  but it destroy everything
* I also use columnWidth: 400 but still the same problem.

Is it possible to define only 3 row ?

For information  after the   <ng-masonry-grid-item tag I don't display an img but a component (with an img inside and some information)  <app-list-item  [indexOfPost]="i" [item]="it"></app-wall-list-item>

Thanks for your help if it's not a bug or feature

**Comment by Shailu4u** [comment]
@gbesset , 
Use custom class on <ng-masonry-grid-item class="my-item" ....>
and write your own CSS (make 3 columns) etc..
.my-item {
    width: 33% !important;
}
Do not modify itemSelector, as this is predefined in ng-masonry-grid.

**Comment by gbesset** [comment]
@Shailu4u  Many thanks !!!
I also tried the 33% but not on that component.... I guess on the wrong one.

now it's OK. have a good day !
