### ISSUE TITLE
Using mat card inside a masonrygirditem gives weird behaviour

### ISSUE THREAD

**Issue by yashwanthkata** [Shailu4u/ng-masonry-grid#9]
I added a mat -card with some mat -buttons in it.Whenever i click a button ,a reorder or some weird animation is happened.This works fine if i use a normal button

**Comment by joffreymaz** [comment]
I'm experiencing the same issue around here

**Comment by Shailu4u** [comment]
Updated playground with angular material 2 components such as mat-card and mat-button. ng-masonry-grid is working fine without any weird animations. Build and run the app as shown in [README.md](https://github.com/Shailu4u/ng-masonry-grid/blob/master/README.md)

**Comment by yashwanthkata** [comment]
Hi @Shailu4u  Thanks for your reply and your time.
Could you please update what changes do we need to make it work if we use  Angular Material

**Comment by Shailu4u** [comment]
All the code changes are in playground folder. Use mat-card component inside ng-masonry-grid-item as shown in app.component.ts.
Remove click handlers if any on ng-masonry-grid-item and add individual click handler on mat-button which is inside the mat-card.
